language: python
sudo: false
python:
  - "2.7"
install:
  - pip install rply
  - pip install coveralls
script:
  coverage run test.py
after_success:
  coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b81f9ec6e179a91aaca0
    on_success: change
    on_failure: always
    on_start: false
