#!/usr/bin/env python

import runac
import optparse, sys, os, subprocess

def tokens(fn, opts):
	for x in runac.tokenize(open(fn)):
		print x

def parse(fn, opts):
	print runac.parse(runac.tokenize(open(fn)))

def generate(fn, opts):
	ir = runac.ir(fn)
	if not opts.test:
		print ir

def compile(fn, opts):
	ir = runac.ir(fn)
	runac.compile(ir, os.path.basename(fn).rsplit('.rns')[0])

COMMANDS = {
	'tokens': tokens,
	'parse': parse,
	'generate': generate,
	'compile': compile,
}

def find(cmd):
	if cmd in COMMANDS: return COMMANDS[cmd]
	matched = sorted(i for i in COMMANDS if i.startswith(cmd))
	if len(matched) == 1:
		return COMMANDS[matched[0]]
	elif len(matched) > 1:
		print 'ambiguous command: %r' % cmd
		return lambda x, y: None
	else:
		print 'no command found: %r' % cmd
		return lambda x, y: None

if __name__ == '__main__':
	parser = optparse.OptionParser(description='The Runa compiler.')
	parser.add_option('--test', help='no output', action='store_true')
	opts, args = parser.parse_args()
	try:
		find(args[0])(args[1], opts)
	except runac.Error as e:
		sys.stderr.write(e.show(args[1]))
